# We can do more optimization here, e.g. job `rust_clippy_check` compiles
# FFmpeg, while `build_and_test` also compiles FFmpeg, that takes a lot of time.
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  rustfmt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # Interestingly clippy check needs to build the crate.
  rust_clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

      - name: Install System FFmpeg
        run: |
          sudo apt-get -y install libavcodec-dev libavdevice-dev \
              libavfilter-dev libavformat-dev libavutil-dev \
              libpostproc-dev libswresample-dev libswscale-dev

      - run: cargo clippy -- -D warnings

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      # https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
      - name: Install FFmpegBuildTools
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
            autoconf \
            automake \
            build-essential \
            cmake \
            git-core \
            libass-dev \
            libfreetype6-dev \
            libgnutls28-dev \
            libsdl2-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev
          sudo apt-get -y install nasm
          sudo apt-get -y install libx264-dev
          sudo apt-get -y install libx265-dev libnuma-dev
          sudo apt-get -y install libvpx-dev
          sudo apt-get -y install libfdk-aac-dev
          sudo apt-get -y install libmp3lame-dev
          sudo apt-get -y install libopus-dev

      - name: Binding Build
        run: cargo build --verbose
      - name: Binding Test
        run: cargo test --verbose
      - name: Build Examples
        run: cargo build --examples --verbose

      - name: Run Slice Example
        run: cargo run --example slice
      # Avoid the situation that example outputs incorrect results.
      # (Is this really essential? Maybe I'm too anxious?)
      - name: Check No Change
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "0"
          else
            echo "1"
          fi

  build_with_cloned_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      # https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
      - name: Install FFmpegBuildTools
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
            autoconf \
            automake \
            build-essential \
            cmake \
            git-core \
            libass-dev \
            libfreetype6-dev \
            libgnutls28-dev \
            libsdl2-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev
          sudo apt-get -y install nasm
          sudo apt-get -y install libx264-dev
          sudo apt-get -y install libx265-dev libnuma-dev
          sudo apt-get -y install libvpx-dev
          sudo apt-get -y install libfdk-aac-dev
          sudo apt-get -y install libmp3lame-dev
          sudo apt-get -y install libopus-dev

      - name: Binding Build
        run: cargo build --verbose

  build_with_prebuilt_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      # https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
      - name: Install FFmpegBuildTools
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
            autoconf \
            automake \
            build-essential \
            cmake \
            git-core \
            libass-dev \
            libfreetype6-dev \
            libgnutls28-dev \
            libsdl2-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev
          sudo apt-get -y install nasm
          sudo apt-get -y install libx264-dev
          sudo apt-get -y install libx265-dev libnuma-dev
          sudo apt-get -y install libvpx-dev
          sudo apt-get -y install libfdk-aac-dev
          sudo apt-get -y install libmp3lame-dev
          sudo apt-get -y install libopus-dev

      - name: FFmpeg Build
        run: |
          git clone https://github.com/ffmpeg/ffmpeg --depth 1
          cd ./ffmpeg
          PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
            --prefix="$HOME/ffmpeg_build" \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$HOME/ffmpeg_build/include" \
            --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
            --extra-libs="-lpthread -lm" \
            --bindir="$HOME/bin" \
            --enable-gpl \
            --enable-libass \
            --enable-libfdk-aac \
            --enable-libfreetype \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-libx264 \
            --enable-libx265 \
            --enable-nonfree && \
          PATH="$HOME/bin:$PATH" make -j$(nproc) && \
          make -j$(nproc) install && \
          hash -r
          cd ..
      - name: Binding Build
        run: PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" cargo build --verbose

  build_with_system_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install System FFmpeg
        run: |
          sudo apt-get -y install libavcodec-dev libavdevice-dev \
              libavfilter-dev libavformat-dev libavutil-dev \
              libpostproc-dev libswresample-dev libswscale-dev

      - name: Binding Build
        run: cargo build --verbose

  # Check if correct documentation can be generated by docs.rs
  docs_rs_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Binding Build
        run: DOCS_RS=1 cargo build --verbose
      - name: Document Generation
        run: cargo doc --verbose
